config/routes.rb
GraciCms::Application.routes.draw do
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
  resources :users
  resources :user_sessions, only: [:new, :create, :destroy]
  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

  resources :posts do
    post :sort, on: :collection
    get :all, on: :collection
    resources :comments
  end

  root 'posts#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user

  validates :content, presence: true
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  validates :title, length: { maximum: 140 }, uniqueness: true
  validates :content, presence: true

  extend ::FriendlyId
  friendly_id :title, use: :slugged

  include RankedModel
  ranks :nav_order

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :comments, dependent: :destroy

  authenticates_with_sorcery!

  validates :password, length: { minimum: 8 }
  validates :password, confirmation: true
  validates :password_confirmation, presence: true

  validates :email, uniqueness: true
  validates :username, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :set_navbar
  before_action :set_admin

  private

    def set_navbar
      @nav_items = Post.rank(:nav_order).where(include_in_nav: true)
    end

    def set_admin
      current_user && current_user.admin == true ? @admin = true : @admin = false
    end

    def check_admin
      unless @admin == true
        redirect_to root_path, notice: 'Must be admin.'
      end
    end

    def authorized_user
      unless @admin == true || @user == current_user
        redirect_to root_url, notice: 'You are not logged in or are logged in as the wrong.'
      end
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post
  before_action :check_admin, only: [:destroy]
  # before_action :require_login, only: [:create]

  def create
    unless current_user
      redirect_back_or_to login_path, notice: "Login required to comment."
    else
      @comment = @post.comments.create(comment_params)
      @comment.update_attribute(:user_id, current_user.id)
      @comment.save
      redirect_to post_path(@post)
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end

  private
    def comment_params
      params.require(:comment).permit(:content)
    end

    def set_post
      @post = Post.friendly.find(params[:post_id])
    end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy, :sort]
  before_action :check_admin, only: [:new, :edit, :create, :update, :destroy, :sort, :all]

  def sort
    @post.update_attribute :nav_order_position, params[:post][:nav_order_position]
    @post.save

    render nothing: true
  end

  def index
    if User.any? == false
      redirect_to new_user_path, notice: 'Create admin user.'
    elsif Post.any?
      @post = Post.rank(:nav_order).first
      @comment = @post.comments.build
      @comments = @post.comments(true)
    else
      redirect_to new_post_path, notice: 'Create first post.'
    end
  end

  def all
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      @post.update_attribute :nav_order_position, Post.maximum("nav_order") + 100
      redirect_to post_path(@post), notice: 'Post created successfully.'
    else
      render nothing: true
    end
  end

  def edit
  end

  def show
    @comment = @post.comments.build
    @comments = @post.comments(true)
  end

  def update
    @post.update_attributes(post_params)
    redirect_to post_path(@post), notice: 'Post edited successfully.'
  end

  def destroy
    @post.destroy
    redirect_to root_path, notice: 'Post deleted successfully.'
  end



  private
    def post_params
      params.require(:post).permit(:title, :content, :include_in_nav, :commentable)
    end

    def set_post
      @post = Post.friendly.find(params[:id])
    end

end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    if login(params[:email], params[:password])
      redirect_back_or_to(root_url, message: 'Logged in successfully.')
    else
      flash.now.alert = "Login failed."
      render action: :new
    end
  end

  def destroy
    logout
    redirect_to(:users, notice: 'Logged out!')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :check_admin, only: [:index]
  before_action :authorized_user, only: [:update, :destroy, :show, :edit]

  # GET /users
  def index
    @users = User.all
  end

  # GET /users/1
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  def create
    @user = User.new(user_params)
    unless User.first
      @user.update_attribute(:admin, "true")
    end
    if @user.save
      auto_login(@user)
      redirect_to root_url, notice: 'User was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /users/1
  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /users/1
  def destroy
    @user.destroy
    redirect_to users_url, notice: 'User was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation, :username)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GraciCms</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>


  <div class="container">
    <%= render "shared/navbar" %>
    <div>
      <p id="notice"><%= flash[:notice] %></p>
      <p id="alert"><%= flash[:alert] %></p>
    </div>
    <%= yield %>
  </div>

</body>
</html>

app/views/posts/_post_form.html.erb
<%= form_for @post, html: {class: "form"} do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :content %>
    <%= f.text_area :content, class: "form-control" %>
  </div>
  <div class="checkbox">
    <%= f.label :include_in_nav do %>
      <%= f.check_box :include_in_nav %> Include in navigation?
    <% end %>
  </div>
  <div class="checkbox">
    <%= f.label :commentable do %>
      <%= f.check_box :commentable %> Allow comments?
    <% end %>
  </div>
  <%= f.submit "Submit", class: "btn btn-default" %>
<% end %>

app/views/posts/all.html.erb
<div class="page-header">
  <%= link_to "new post", new_post_path, class: "btn btn-primary pull-right" %>
  <h1>All Posts</h1>
</div>


<% @posts.each do |post| %>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">
        <%= link_to post.title, post_path(post) %>
      </h3>
    </div>
    <div class="panel-body">
      <%= post.content %><br>
      <%= link_to("#{pluralize post.comments.length, "comment"}", post) if post.comments.length > 0 %>
      <div class="pull-right">
        <%= link_to "edit", edit_post_path(post), class: "btn btn-default btn-xs" %>
        <%= link_to post, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-default btn-xs" do %>
          <span class="glyphicon glyphicon-trash"></span>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/posts/edit.html.erb
<div class="page-header">
  <h1>Edit Post</h1>
</div>

<p class="text-warning">Note: editing the title doesn't change the Post URL</p>
<%= render partial: 'post_form' %>

app/views/posts/index.html.erb
<%= render "shared/post" %>

app/views/posts/new.html.erb
<div class="page-header">
  <h1>New Post</h1>
</div>

<%= render partial: 'post_form' %>

app/views/posts/show.html.erb
<%= render "shared/post" %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <ul id="sortable" class="nav navbar-nav" update_url="<%= sort_posts_path %>" >
    <% @nav_items.each do |post| %>
      <% if post.include_in_nav? %>
        <li data-post-id="<%= post.id %>" class="<%= @admin ? 'item' : '' %>">
            <%= link_to post.title, post_path(post) %>
        </li>
      <% end %>
    <% end %>

    <% if current_user %>
      <% if current_user.admin == true %>
        <li>
          <%= link_to new_post_path do %>
            <span class="glyphicon glyphicon-pencil"></span> New Post
          <% end %>
        </li>
        <li>
          <%= link_to all_posts_path do %>
            All Posts
          <% end %>
        </li>
      <% end %>
      <li>
        <%= link_to "Edit Profile", edit_user_path(current_user.id) %>
      </li>
      <li>
        <%= link_to "Logout", :logout, method: :post %>
      </li>
    <% else %>
      <li>
        <%= link_to "Register", new_user_path %>
      </li>
      <li>
        <%= link_to "Login", :login %>
      </li>
    <% end %>
  </ul>
</nav>

app/views/shared/_post.html.erb
<h1>
  <%= @post.title %>
</h1>

<div class="panel panel-default">
  <div class="panel-body">
    <%= @post.content %>
    <% if @admin == true %>
      <div class="pull-right">
        <%= link_to "edit", edit_post_path(@post), class: "btn btn-default btn-xs" %>
        <%= link_to @post, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-default btn-xs" do %>
          <span class="glyphicon glyphicon-trash"></span>
        <% end %>
      </div>
    <% end %>
  </div>
</div>
<% unless @comments.empty? %>
  <h2>Comments</h2>
    <% @comments.each do |comment| %>
      <div class="panel panel-default">
        <div class="panel-body">
          <%= comment.content %>
          <% if @admin == true %>
            <%= link_to [@post, comment], method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-default btn-xs pull-right" do %>
              <span class="glyphicon glyphicon-trash"></span>
            <% end %>
          <% end %>
        </div>
        <div class="panel-footer">
          by <%= comment.user.username %>, <%= time_ago_in_words(comment.created_at) %> ago
        </div>
      </div>
    <% end %>
<% end %>

<br>
<% if @post.commentable == true %>
  <%= form_for [@post, @comment], html: {class: "form"} do |f| %>
    <div class="form-group">
      <%= f.label :content, "Comment" %>
      <%= f.text_field :content, class: "form-control" %>
    </div>
    <%= f.submit "Submit comment", class: "btn btn-default" %>
  <% end %>
<% elsif @post.commentable == false && @comments.any? %>
  <em>Comments are now closed</em>
<% end %>

app/views/user_sessions/_form.html.erb
<%= form_tag user_sessions_path, :method => :post do %>
  <div class="field">
    <%= label_tag :email %><br />
    <%= text_field_tag :email %>
  </div>
  <div class="field">
    <%= label_tag :password %><br />
    <%= password_field_tag :password %>
  </div>
  <div class="actions">
    <%= submit_tag "Login" %>
  </div>
<% end %>

app/views/user_sessions/create.html.erb
<h1>UserSessions#create</h1>
<p>Find me in app/views/user_sessions/create.html.erb</p>

app/views/user_sessions/destroy.html.erb
<h1>UserSessions#destroy</h1>
<p>Find me in app/views/user_sessions/destroy.html.erb</p>

app/views/user_sessions/new.html.erb
<h1>Login</h1>

<%= render 'form' %>

<%= link_to 'Back', user_sessions_path %>

app/views/users/edit.html.erb
<h1>Editing user <strong><%= @user.username %></strong></h1>

<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Show', @user %>

app/views/users/index.html.erb
<h1>All Users</h1>

<table>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
    <p class="help-block">This cannot be changed.</p>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/show.html.erb
<p>
  <strong>User:</strong>
  <%= @user.username %><br>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>